### PR TITLE
Fix #38 log all errors, even without text property

### LINKED ISSUE #38: Crashing on Windows 10 for iOS
image

And Git tells that not a single modification has been done

### PR DESCRIPTION
**Pull request by suside**
let me know what you think

### CODE REVIEW

**Comment by stovmascript** [comment]
Thanks for the PR. Looks like a good fix for the logging... I'd like to keep the #38 open though, until we fix the crashing issue.

**Comment by stovmascript** [comment]
Ah, could you swap out the spread operators for `Object.assign` for now please?

**Comment by stovmascript** [comment]
Also, please run `npm install` or `yarn` to fetch project dev tools with before committing.

File: index.js [hunk 1]
```diff
@@ -396,7 +396,7 @@ function version(program, projectPath) {
 					}, [])
 					.forEach(function(err) {
 						if (program.outputHelp) {
-							err.text && log(err);
+							log({ ...{ style: 'red', text: String(err) }, ...err });
```
Comment (stovmascript) [inline index.js]: How about this?

```js
log(Object.assign({}, { style: "red", text: err.toString() }));
```

**Comment by stovmascript** [comment]
@suside Understood and great. Thanks for your contribution. Merging and releasing now.
